### ISSUE TITLE
Location of ufw's user.rules file is different on different systems

### ISSUE THREAD

**Issue by joelanders** [equalitie/autodeflect#8]
On my Debian 9 system, the man page for `ufw-framework` says the location is `/etc/user[6].rules`.
The Internet says Ubuntu 16.04 does `/etc/ufw/user.rules`.
`deploy.sh` assumes `/lib/ufw/user.rules`, which must be right for another system.

```
-USERINPUT=/lib/ufw/user.rules
+USERINPUT=/etc/user.rules
```
this gets `deploy.sh` past that step, corroborating the man page's claim :)
EDIT: turns out the man page was actually wrong and the path is `/etc/ufw/user.rules` (which makes more sense). `deploy.sh` should maybe check the firewall's running and actually blocking something?

**Comment by RamJett** [comment]
deploy.sh is now depreciated.
